// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "Get products list",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/GetProductsList"
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "getProductById",
        "description": "Get product by id",
        "operationId": "getProductById.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/GetProductByIdSuccess"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/GetProductByIdFailed"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "GetProductByIdSuccess": {
      "properties": {
        "product": {
          "$ref": "#/definitions/Product",
          "title": "GetProductByIdSuccess.product"
        },
        "event": {
          "additionalProperties": false,
          "title": "GetProductByIdSuccess.event",
          "type": "object"
        }
      },
      "required": [
        "product",
        "event"
      ],
      "additionalProperties": false,
      "title": "GetProductByIdSuccess",
      "type": "object"
    },
    "GetProductByIdFailed": {
      "properties": {
        "message": {
          "title": "GetProductByIdFailed.message",
          "type": "string"
        },
        "event": {
          "additionalProperties": false,
          "title": "GetProductByIdFailed.event",
          "type": "object"
        }
      },
      "required": [
        "message",
        "event"
      ],
      "additionalProperties": false,
      "title": "GetProductByIdFailed",
      "type": "object"
    },
    "GetProductsList": {
      "properties": {
        "products": {
          "items": {
            "$ref": "#/definitions/Product",
            "title": "GetProductsList.products.[]"
          },
          "title": "GetProductsList.products",
          "type": "array"
        },
        "event": {
          "additionalProperties": false,
          "title": "GetProductsList.event",
          "type": "object"
        }
      },
      "required": [
        "products",
        "event"
      ],
      "additionalProperties": false,
      "title": "GetProductsList",
      "type": "object"
    },
    "Product": {
      "properties": {
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};